include $(GNUSTEP_MAKEFILES)/common.make

PRINT_PROJECT_NAME = NO

BUNDLE_NAME = TestBundle

$(BUNDLE_NAME)_BUNDLE_LIBS = -lUnitKit $(FND_LIBS)

$(BUNDLE_NAME)_HEADER_FILES = TestOne.h TestTwo.h TestThree.h

$(BUNDLE_NAME)_OBJC_FILES = TestOne.m TestTwo.m TestThree.m

include $(GNUSTEP_MAKEFILES)/bundle.make
-include ../../../../../etoile.make
