include $(GNUSTEP_MAKEFILES)/common.make

PRINT_PROJECT_NAME = NO

BUNDLE_NAME = UnitKitTests

$(BUNDLE_NAME)_BUNDLE_LIBS = -lUnitKit -lTestFramework $(FND_LIBS)

$(BUNDLE_NAME)_OBJC_FILES = $(wildcard *.m)

include $(GNUSTEP_MAKEFILES)/bundle.make
-include ../../../../../etoile.make
