include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = UnitKitTests

$(BUNDLE_NAME)_BUNDLE_LIBS = -lUnitKit $(FND_LIBS)

$(BUNDLE_NAME)_OBJC_FILES = $(wildcard *.m)

include $(GNUSTEP_MAKEFILES)/bundle.make
-include ../../../../../etoile.make
