include $(GNUSTEP_MAKEFILES)/common.make

ADDITIONAL_OBJCFLAGS = -Wno-import

BUNDLE_NAME = TestBundle

TestBundle_LIBRARIES_DEPEND_UPON = -lUnitKit -lgnustep-base

TestBundle_HEADER_FILES = TestOne.h TestTwo.h TestThree.h

TestBundle_OBJC_FILES = TestOne.m TestTwo.m TestThree.m

include $(GNUSTEP_MAKEFILES)/bundle.make


