include $(GNUSTEP_MAKEFILES)/common.make

FRAMEWORK_NAME= UnitKit

UnitKit_OBJC_FILES = UKRunner.m UKTestHandler.m  
UnitKit_HEADER_FILES= UKRunner.h UKTest.h UKTestHandler.h UnitKit.h
UnitKit_HEADER_FILES_INSTALL_DIR = /UnitKit
UnitKit_LOCALIZED_RESOURCE_FILES = UKRunner.strings UKTestHandler.strings
UnitKit_LANGUAGES = English

ADDITIONAL_OBJCFLAGS= -Wall -Wno-import

include $(GNUSTEP_MAKEFILES)/framework.make


