include $(GNUSTEP_MAKEFILES)/common.make

PRINT_PROJECT_NAME = NO

TOOL_NAME = ukrun

ukrun_TOOL_LIBS = -lUnitKit $(FND_LIBS)

ukrun_OBJC_FILES = main.m

include $(GNUSTEP_MAKEFILES)/tool.make
-include ../../../../etoile.make
